"""Add date to Race model

Revision ID: 7976ae61fc4e
Revises: b46369b2b9ac
Create Date: 2024-06-05 22:30:31.437273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7976ae61fc4e'
down_revision = 'b46369b2b9ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
